[platformio]
default_envs = esp32-s3-devkitc-1
data_dir = data

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.partitions = partitions_16MB.csv
board_build.filesystem = littlefs
board_upload.flash_size = 16MB

build_flags =
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -DTONEX_MDNS_NAME=\"tonex\"
    -DTONEX_AP_SSID=\"ToneX-Remote\"
    -DTONEX_AP_PASS=\"\"

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.4
    mathieucarbou/ESPAsyncWebServer @ ^3.3.23
    mathieucarbou/AsyncTCP @ ^3.2.14

[env:native]
platform = native
test_framework = unity
build_src_filter =
    +<tonex_hdlc.cpp>
build_flags =
    -std=c++17
    -DNATIVE_TEST
